INSERT INTO tblEpisodeLink (sitcomID,season,link) VALUES
(2,1,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 1/.DS_Store'),
(2,1,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 1/BIG_BANG_THEORY_DISC_1.Title1.avi'),
(2,1,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 1/BIG_BANG_THEORY_DISC_2.Title1.avi'),
(2,1,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 1/BIG_BANG_THEORY_DISC_3.Title1.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 201 - The Bad Fish Paradigm.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 202 - The Codpiece Topology.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 203 - The Barbarian Sublimation.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 204 - The Griffin Equivalency.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 205 - The Euclid Alternative.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 206 - The Cooper-Nowitzki Theorem.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 207 - The Panty Pinata Polarization.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 208 - The Lizard-spock Expansion.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 209 - The White Asparagus Triangulation.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 210 - The Vartabedian Conundrum.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 211 - The Bath Item Gift Hypothesis.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 212 - The Killer Robot Instability.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 213 - The Friendship Algorithm.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 214 - The Financial Permeability.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 215 - The Maternal Capacitance.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 216 - The Cushion Saturation.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 217 - The Terminator Decoupling.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 218 - The Work Song Nanocluster.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 220 - The Hofstadter Isotope.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 221 - The Vegas Renormalization.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 222 - The Classified Materials Turbulence.avi'),
(2,2,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 2/The Big Bang Theory - 223 - The Monopolar Expedition.avi'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E01 - The Electric Can Opener Fluctuation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E02 - The Jiminy Conjecture.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E03 - The Gothowitz Deviation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E04 - The Pirate Solution.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E05 - The Creepy Candy Coating Corollary.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E06 - The Cornhusker Vortex.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E07 - The Guitarist Amplification.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E08 - The Adhesive Duck Deficiency.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E09 - The Vengeance Formulation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E10 - The Gorilla Experiment.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E11 - The Maternal Congruence.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E12 - The Psychic Vortex.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E13 - The Bozeman Reaction.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E14 - The Einstein Approximation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E15 - The Large Hadron Collision.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E16 - The Excelsior Acquisition.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E17 - The Precious Fragmentation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E18 - The Pants Alternative.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E19 - The Wheaton Recurrence.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E20 - The Spaghetti Catalyst.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E21 The Plimpton Stimulation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E22 - The Staircase Implementation.mkv'),
(2,3,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 3/The Big Bang Theory S03E23 - The Lunar Excitation.mkv'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E01 - The Robotic Manipulation.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E02 - The Cruciferous Vegetable Amplification.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E03 - The Zazzy Substitution.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E04 - The Hot Troll Deviation.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E05 - The Desperation Emanation.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E06 - The Irish Pub Formulation.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E07 - The Apology Insufficiency.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E08 - The 21-second Excitation.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E09 - The Boyfriend Complexity.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E10 - The Alien Parasite Hypothesis.mp4'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E11 - The Justice League Recombination.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E12 - The Bus Pants Utilization.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E13 - The Love Car Displacement.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E14 - The Thespian Catalyst.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E15 - The Benefactor Factor.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E16 - The Cohabitation Formulation.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E17 - The Toast Derivation.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E18 - The Prestidigitation Approximation.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E19 - The Zarnecki Incursion.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E20 - The Herb Garden Germination.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E21 - The Agreement Dissection.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E22 - The Wildebeest Implementation.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E23 - The Engagement Reaction.avi'),
(2,4,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 4/The Big Bang Theory S04E24 - The Roomate Transmogrfication.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory - It All Started With A Big Bang.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E01 - The Skank Reflex Analysis.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E02 - The Infestation Hypothesis.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E03 - The Pulled Groin Extrapolation.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E04 - The Wiggly Finger Catalyst.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E05 - The Russian Rocket Reaction.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E06 - The Rhinitis Revelation.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E07 - The Good Guy Fluctuation.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E08 - The Isolation Permutation.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E09 - The Ornithophobia Diffusion.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E10 - The Flaming Spittoon Acquisition.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E11 - The Speckerman Recurrence.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E12 - The Shiny Trinket Maneuver.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S04E13 - The Recombination Hypothesis.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E14 - The Beta Test Initiation.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E15 - The Friendship Contraction.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E16 - The Vacation Solution.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E17 - The Rothman Disintegration.avi'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E18 - The Werewolf Transformation.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E19 - The Weekend Vortex.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E20 - The Transporter Malfunction.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E21 - The Hawking Excitation.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E22 - The Stag Convergence.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E23 - The Launch Acceleration.mp4'),
(2,5,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 5/The Big Bang Theory S05E24 - The Countdown Reflection.mp4'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E01.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E02.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E03.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E04.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E05.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E06.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E07.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E08.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E09.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E10.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E11.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E12.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E13.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E14.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E15.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E16.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E17.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E18.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E19.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E20.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E21.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E22.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E23.HDTV.XviD-AFG.avi'),
(2,6,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 6/The.Big.Bang.Theory.S06E24.HDTV.XviD-AFG.avi'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E01.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E02.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E03.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E04.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E05.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E06.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E07.HDTV.x264-LOL.[VTV].mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E08.HDTV.X264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E09.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E10.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E11.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E12.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E13.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E14.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E15.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E16.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E17.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E18.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E19.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E20.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E21.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E22.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E23.HDTV.x264-LOL.mp4'),
(2,7,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 7/The.Big.Bang.Theory.S07E24.HDTV.x264-LOL.mp4'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/.DS_Store'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E01.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E02.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E03.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E04.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E05.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E06.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E07.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E08.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E09.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E10.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E11.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E12.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E13.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E14.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E15.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E16.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E17.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E18.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E19.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E20.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E21.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E22.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E23.720p.HDTV.X264-MRSK.mkv'),
(2,8,'/Users/tusharsaurabh/Documents/Sitcoms/The Big Bang Theory/Season 8/The.Big.Bang.Theory.S08E24.720p.HDTV.X264-MRSK.mkv'),
