INSERT INTO tblEpisodeLink (sitcomID,season,link) VALUES
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x01] - The One where Monica gets a Roommate.mp4'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x02] - The One with the Sonogram at the End.mp4'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x03] - The One with the Thumb.mp4'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x04] - The One with George Stephanopoulos.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x05] - The One with the East German Laundry Detergent.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x06] - The One with the Butt.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x07] - The One with the Blackout.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x08] - The One where Nana dies Twice.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x09] - The One where Underdog gets Away.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x10] - The One with the Monkey.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x11] - The One with Mrs. Bing.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x12] - The One with the Dozen Lasagnas.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x13] - The One with the Boobies.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x14] - The One with the Candy Hearts.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x15] - The One with the Stoned Guy.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x16 - 1x17] - The One with Two Parts.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x18] - The One with all the Poker.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x19] - The One where the Monkey gets Away.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x20] - The One with the Evil Orthodontist.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x21] - The One with the Fake Monica.mkv'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x22] - The One with the Ick Factor.mp4'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x23] - The One with the Birth.mp4'),
(1,1,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 1/Friends - [1x24] - The One where Rachel finds Out.mp4'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e01.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e02.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e03.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e04.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e05.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e06.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e07.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e08.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e09.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e10.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e11.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e12.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e13.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e14.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e15.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e16.720p.bluray.sujaidr.mkv'),
(1,10,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 10/friends.s10e17e18.720p.bluray.sujaidr.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x01] - The One with Ross\'s New Girlfriend.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x02] - The One with the Breast Milk.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x03] - The One Where Heckles Dies.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x04] - The One with Phoebe\'s Husband.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x05] - The One with Five Steaks and an Eggplant.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x06] - The One with the Baby on the Bus.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x07] - The One Where Ross Finds Out.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x08] - The One with the List.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x09] - The One with Phoebe\'s Dad.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x10] - The One with Russ.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x11] - The One with the Lesbian Wedding.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x12 - x13] - The One After the Superbowl.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x14] - The One with the Prom Video.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x15] - The One Where Ross and Rachel... You Know.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x16] - The One Where Joey Moves Out.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x17] - The One Where Eddie Moves In.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x18] - The One Where Dr. Ramoray Dies.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x19] - The One Where Eddie Won\'t Go.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x20] - The One Where Old Yeller Dies.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x21] - The One with the Bullies.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x22] - The One with the Two Parties.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x23] - The One with the Chicken Pox.mkv'),
(1,2,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 2/Friends - [2x24] - The One with Barry and Mindy\'s Wedding.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/.DS_Store'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x01] - The One with the Princess Leia Fantasy.mp4'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x02] - The One Where No One\'s Ready + Audio Commentary.mp4'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x03] - The One with the Jam.mp4'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x04] - The One with the Metaphorical Tunnel.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x05] - The One with Frank Jr.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x06] - The One with the Flashback.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x07] - The One with the Race Car Bed.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x08] - The One with the Giant Poking Device.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x09] - The One with the Football + Audio Commentary.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x10] - The One Where Rachel Quits.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x11] - The One Where Chandler Can\'t Remember Which Sister.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x12] - The One With All The Jealousy.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x13] - The One Where Monica and Richard Are Just Friends.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x14] - The One with Phoebe\'s Ex-Partner.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x15] - The One Where Ross and Rachel Take a Break.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x16] - The One the Morning After+ Audio Commentary.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x17] - The One Without the Ski Trip.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x18] - The One with the Hypnosis Tape.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x19] - The One with the Tiny T-Shirt.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x20] - The One with the Dollhouse.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x21] - The One with the Chick and the Duck.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x22] - The One with the Screamer.mkv'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x23] - The One with Ross\'s Thing.mp4'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x24] - The One with the Ultimate Fighting Champion.mp4'),
(1,3,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 3/Friends - [3x25] - The One at the Beach.mp4'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/.DS_Store'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/eng subtitles'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e01.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e02.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e03.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e04.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e05.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e06.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e07.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e08.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e09.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e10.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e11.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e12.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e13.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e14.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e15.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e16.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e17.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e18.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e19.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e20.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e21.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e22.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e23.720p.bluray.x264-sujaidr.mkv'),
(1,4,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 4/friends.s04e24.720p.bluray.x264-sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e01.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e02.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e03.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e04.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e05.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e06.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e07.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e08.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e09.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e10.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e11.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e12.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e13.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e14.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e15.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e16.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e17.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e18.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e19.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e20.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e21.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e22.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e23.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,5,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 5/friends.s05e24.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e01.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e02.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e03.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e04.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e05.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e06.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e07.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e08.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e09.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e10.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e11.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e12.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e13.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e14.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e15.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e16.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e17.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e18.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e19.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e20.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e21.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e22.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e23.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e24.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,6,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 6/friends.s06e25.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x01] - The One with Monica\'s Thunder.mp4'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x02] - The One with Rachel\'s Book.mp4'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x03] - The One with Phoebe\'s Cookies.mp4'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x04] - The One with Rachel\'s Assistant.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x05] - The One with the Engagement Picture.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x06] - The One with the Nap Partners.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x07] - The One with Ross\' Library Book.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x08] - The One Where Chandler Doesn\'t Like Dogs.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x09] - The One with All the Candy.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x10] - The One with the Holiday Armadillo + Audio Commentary.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x11] - The One with All the Cheesecakes.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x12] - The One Where They\'re Up All Night.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x13] - The One Where Rosita Dies.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x14] - The One Where They All Turn Thirty.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x15] - The One with Joey\'s New Brain.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x16] - The One with the Truth About London.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x17] - The One with the Cheap Wedding Dress.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x18] - The One with Joey\'s Award.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x19] - The One with Ross and Monica\'s Cousin.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x20] - The One with Rachel\'s Big Kiss.mkv'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x22] - The One with Chandler\'s Dad.mp4'),
(1,7,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 7/Friends - [7x23-24] - The One with Monica and Chandler\'s Wedding + Audio Commentary.mp4'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e01.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e02.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e03.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e04.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e05.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e06.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e07.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e08.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e09.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e10.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e11.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e12.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e13.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e14.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e15.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e16.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e17.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e18.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e19.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e20.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e21.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e22.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e23.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,8,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 8/friends.s08e24.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e01.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e02.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e03.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e04.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e05.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e06.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e07.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e08.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e09.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e10.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e11.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e12.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e13.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e14.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e15.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e16.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e17.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e18.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e19.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e20.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e21.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e22.720p.bluray.x264-mrs.sujaidr.mkv'),
(1,9,'/Users/tusharsaurabh/Documents/Sitcoms/Friends/Season 9/friends.s09e23e24.720p.bluray.x264-mrs.sujaidr.mkv')
